# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

#    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout
      - run:
          name: Run build with tests
          command:  if [[ -z "$GIT_USER_EMAIL" ]]; then  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -U -nsu -Dgpg.skip --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn ;fi
      - run:
           name: Save test results
           command: |
                  mkdir -p ~/junit/
                  find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
           when: always
      - store_test_results:
            path: ~/junit
      - store_artifacts:
            path: ~/junit
      - run:
            name: Save artifacts
            command: |
                    mkdir -p ~/artifacts/
                    find . -type f -regex ".*/target/.*jar" -exec cp {} ~/artifacts/ \;
            when: always
      - store_test_results:
            path: ~/artifacts
      - store_artifacts:
            path: ~/artifacts